# Metorial Workspace - Serena Project Configuration
# https://github.com/oraios/serena
#
# This is a coordinated polyrepo workspace containing:
# - metorial: MCP server catalog (TypeScript/Bun)
# - metorial-platform: Core platform with mcp-engine (TypeScript + Go)
# - metorial-index: Server registry (TypeScript/Bun)
# - metorial-docs: Documentation (Mintlify/MDX)

# Language servers to start for semantic code understanding
# TypeScript handles JS/TS across all repos, Go handles mcp-engine
languages:
  - typescript
  - go

# Text file encoding
encoding: "utf-8"

# Use .gitignore files for ignore patterns
ignore_all_files_in_gitignore: false

# Additional paths to ignore for optimal language server performance
ignored_paths:
  # =============================================================================
  # DEPENDENCIES
  # =============================================================================
  - "**/node_modules/**"
  - "**/vendor/**"
  - "**/jspm_packages/**"
  - "**/web_modules/**"
  - "**/bower_components/**"

  # =============================================================================
  # BUILD OUTPUTS
  # =============================================================================
  - "**/dist/**"
  - "**/build/**"
  - "**/.next/**"
  - "**/.turbo/**"
  - "**/target/**"
  - "**/.nuxt/**"
  - "**/out/**"
  - "**/bin/**"
  - "**/.vuepress/dist/**"
  - "**/.vitepress/dist/**"

  # =============================================================================
  # CACHE DIRECTORIES
  # =============================================================================
  - "**/.cache/**"
  - "**/cache/**"
  - "**/.parcel-cache/**"
  - "**/.rpt2_cache/**"
  - "**/.rts2_cache_cjs/**"
  - "**/.rts2_cache_es/**"
  - "**/.rts2_cache_umd/**"
  - "**/.vitepress/cache/**"
  - "**/.npm/**"
  - "**/.eslintcache"
  - "**/.stylelintcache"
  - "**/*.tsbuildinfo"

  # =============================================================================
  # GENERATED FILES
  # =============================================================================
  - "**/*.generated.*"
  - "**/generated/**"

  # =============================================================================
  # TEST COVERAGE
  # =============================================================================
  - "**/coverage/**"
  - "*.lcov"
  - "**/lib-cov/**"
  - "**/.nyc_output/**"

  # =============================================================================
  # RUNTIME DATA
  # =============================================================================
  - "**/pids/**"
  - "**/*.pid"
  - "**/*.seed"
  - "**/*.pid.lock"

  # =============================================================================
  # IDE/TOOL DIRECTORIES
  # =============================================================================
  - "**/.idea/**"
  - "**/.vscode/**"
  - "**/.vscode-test/**"
  - "**/*.swp"
  - "**/*.swo"

  # =============================================================================
  # FRAMEWORK/TOOL SPECIFIC
  # =============================================================================
  - "**/.grunt/**"
  - "**/.docusaurus/**"
  - "**/.serverless/**"
  - "**/.fusebox/**"
  - "**/.dynamodb/**"
  - "**/.tern-port"

  # =============================================================================
  # YARN V2 / PNP
  # =============================================================================
  - "**/.yarn/cache/**"
  - "**/.yarn/unplugged/**"
  - "**/.yarn/build-state.yml"
  - "**/.yarn/install-state.gz"
  - "**/.pnp.*"
  - "**/.yarn-integrity"

  # =============================================================================
  # PYTHON (metorial-platform)
  # =============================================================================
  - "**/__pycache__/**"
  - "**/*.py[cod]"
  - "**/*$py.class"
  - "**/*.so"
  - "**/.Python/**"
  - "**/develop-eggs/**"
  - "**/eggs/**"
  - "**/.eggs/**"
  - "**/sdist/**"
  - "**/wheels/**"
  - "**/*.egg-info/**"
  - "**/*.egg"
  - "**/venv/**"
  - "**/ENV/**"

  # =============================================================================
  # DOCUMENTATION BUILD
  # =============================================================================
  - "metorial-docs/.mintlify/**"
  - "metorial-docs/"

  # =============================================================================
  # WORKSPACE SPECIFIC
  # =============================================================================
  - ".scratchpad/**"
  - ".local_docs/**"
  - "schema/**"
  - ".serena/cache"
  - ".claude/settings.local.json"
  - ".mise/installs/"
  - ".mise/cache/"
  - ".mise/shims/"

  # =============================================================================
  # LOGS
  # =============================================================================
  - "*.log"
  - "**/logs/**"

  # =============================================================================
  # ENVIRONMENT & SECRETS
  # =============================================================================
  - ".env"
  - ".env.local"
  - ".env.*.local"
  - "*.pem"
  - "*.key"
  - "mise.local.toml"
  - "**/env.json"

  # =============================================================================
  # OS & EDITOR FILES
  # =============================================================================
  - "*.code-workspace.local"
  - ".DS_Store"
  - ".DS_Store?"
  - "._*"
  - ".Spotlight-V100"
  - ".Trashes"
  - "Thumbs.db"

  # =============================================================================
  # MISC BUILD ARTIFACTS
  # =============================================================================
  - "**/*.tgz"
  - "**/index.db"

# Allow editing (not read-only)
read_only: false

# No tools excluded - use full Serena capability
excluded_tools: []

# Initial prompt provided when project is activated
initial_prompt: |
  This is the Metorial workspace - a coordinated polyrepo for an open-source
  integration platform for agentic AI built on the Model Context Protocol (MCP).

  Key repositories:
  - metorial/: MCP server catalog with 33+ custom servers
  - metorial-platform/: Core platform (TypeScript + Go mcp-engine)
  - metorial-index/: Server discovery registry
  - metorial-docs/: Documentation site (Mintlify)

  Tooling: Uses mise-en-place for unified tool management, Bun as runtime,
  Turbo for builds. Run `mise tasks` to see available commands.

# Project name for reference within Serena
project_name: "metorial-workspace"

# Include optional tools
included_optional_tools: []

# Use default modes (editing, interactive)
base_modes:

default_modes:

# No fixed tool restrictions
fixed_tools: []
